apiVersion: cyclonedx/v1.4
kind: BillOfMaterials
metadata:
  name: merged
  version: "1.0.0"
  timestamp: "2025-07-18T00:00:00Z"
spec:
  supportGroupId: ab1234
  financeAppId: ab1234
  bomFormat: CycloneDX
  specVersion: "1.4"
  serialNumber: "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79"
  version: 1
  operatingContext:
    contextVersion: 'v1.0.1'
    envResources:
    -name: mergedb
      kind: s3bucket
      access: CR
    -name: mergedrds
      kind: auroraRds
      auroraRdsMachineSize: MINI
      auroraDbPort: 5435
      auroraDbVersion: '15.12'

  metadata:
    timestamp: "2025-07-18T00:00:00Z"
    tools:
      - vendor: "Example Corp"
        name: "BOM Generator"
        version: "1.0.0"
    component:
      type: application
      name: sample-application
      version: "1.0.0"
      description: "Sample application for demonstration"
  components:
    - type: library
      name: spring-boot-starter-web
      version: "3.1.0"
      scope: required
      purl: "pkg:maven/org.springframework.boot/spring-boot-starter-web@3.1.0"
    - type: library
      name: spring-boot-starter-actuator
      version: "3.1.0"
      scope: required
      purl: "pkg:maven/org.springframework.boot/spring-boot-starter-actuator@3.1.0"
    - type: library
      name: junit-jupiter
      version: "5.9.0"
      scope: test
      purl: "pkg:maven/org.junit.jupiter/junit-jupiter@5.9.0"
  workloadList:
  -name: common
    kind: helm
    workloadVersion: 'v1.0.1'
    deployFirst: true
    helm:
      chartRepoUrl: pdm-ba0270-ops
      chartPath: merged/merged/common
      chartVersion: "1.0.0"
      valuesPath: merged/merged/values/values-$ENV.yaml
      revision: develop
  - name: helm-cd3456
    kind: helm
    options:
      setString:
        - cd3456Svc.ImageTag=$CONTAINER_IMAGE_TAG
    helm:
      chartRepoUrl: pdm-ba0270-ops
      chartPath: merged/merged/helm
      chartVersion: 1.0.1
      valuesPath: merged/merged/values/values-$ENV.yaml
      revision: develop
